spring:
  application:
    name: gateway

  cloud:
    loadbalancer:
      enabled: true

    gateway:
      server:
        webflux:
          routes:
            - id: medicos
              uri: lb://medicos
              predicates:
                - Path=/api/medicos/**
              filters:
                - StripPrefix=2

            - id: paciente
              uri: lb://paciente
              predicates:
                - Path=/api/pacientes/**
              filters:
                - StripPrefix=2

            - id: citas
              uri: lb://citas
              predicates:
                - Path=/api/citas/**
              filters:
                - StripPrefix=2

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true